# Clock signal
set_property PACKAGE_PIN Y18 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]

# Reset signal
set_property PACKAGE_PIN P20 [get_ports reset]
set_property IOSTANDARD LVCMOS33 [get_ports reset]
# Start Uart communicate signal
set_property PACKAGE_PIN Y8 [get_ports start_uart]
set_property IOSTANDARD LVCMOS33 [get_ports start_uart]

# imm input
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input[15]}]

set_property PACKAGE_PIN W4 [get_ports {imm_input[0]}]
set_property PACKAGE_PIN R4 [get_ports {imm_input[1]}]
set_property PACKAGE_PIN T4 [get_ports {imm_input[2]}]
set_property PACKAGE_PIN T5 [get_ports {imm_input[3]}]
set_property PACKAGE_PIN U5 [get_ports {imm_input[4]}]
set_property PACKAGE_PIN W6 [get_ports {imm_input[5]}]
set_property PACKAGE_PIN W5 [get_ports {imm_input[6]}]
set_property PACKAGE_PIN U6 [get_ports {imm_input[7]}]
set_property PACKAGE_PIN V5 [get_ports {imm_input[8]}]
set_property PACKAGE_PIN R6 [get_ports {imm_input[9]}]
set_property PACKAGE_PIN T6 [get_ports {imm_input[10]}]
set_property PACKAGE_PIN Y6 [get_ports {imm_input[11]}]
set_property PACKAGE_PIN AA6 [get_ports {imm_input[12]}]
set_property PACKAGE_PIN V7 [get_ports {imm_input[13]}]
set_property PACKAGE_PIN AB7 [get_ports {imm_input[14]}]
set_property PACKAGE_PIN AB6 [get_ports {imm_input[15]}]



# LED output

set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[14]}]
set_property IOSTANDARD LVCMOS33 [get_ports {imm_input_led[15]}]

set_property PACKAGE_PIN A21 [get_ports {imm_input_led[0]}]
set_property PACKAGE_PIN E22 [get_ports {imm_input_led[1]}]
set_property PACKAGE_PIN D22 [get_ports {imm_input_led[2]}]
set_property PACKAGE_PIN E21 [get_ports {imm_input_led[3]}]
set_property PACKAGE_PIN D21 [get_ports {imm_input_led[4]}]
set_property PACKAGE_PIN G21 [get_ports {imm_input_led[5]}]
set_property PACKAGE_PIN G22 [get_ports {imm_input_led[6]}]
set_property PACKAGE_PIN F21 [get_ports {imm_input_led[7]}]
set_property PACKAGE_PIN J17 [get_ports {imm_input_led[8]}]
set_property PACKAGE_PIN L14 [get_ports {imm_input_led[9]}]
set_property PACKAGE_PIN L15 [get_ports {imm_input_led[10]}]
set_property PACKAGE_PIN L16 [get_ports {imm_input_led[11]}]
set_property PACKAGE_PIN K16 [get_ports {imm_input_led[12]}]
set_property PACKAGE_PIN M15 [get_ports {imm_input_led[13]}]
set_property PACKAGE_PIN M16 [get_ports {imm_input_led[14]}]
set_property PACKAGE_PIN M17 [get_ports {imm_input_led[15]}]


set_property PACKAGE_PIN N19 [get_ports {led_output[0]}]
set_property PACKAGE_PIN N20 [get_ports {led_output[1]}]
set_property PACKAGE_PIN M20 [get_ports {led_output[2]}]
set_property PACKAGE_PIN K13 [get_ports {led_output[3]}]
set_property PACKAGE_PIN K14 [get_ports {led_output[4]}]
set_property PACKAGE_PIN M13 [get_ports {led_output[5]}]
set_property PACKAGE_PIN L13 [get_ports {led_output[6]}]
set_property PACKAGE_PIN K17 [get_ports {led_output[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led_output[7]}]


# Display Segment and Digit Select Output
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {segment_output[6]}]

set_property PACKAGE_PIN F15 [get_ports {segment_output[0]}]
set_property PACKAGE_PIN F13 [get_ports {segment_output[1]}]
set_property PACKAGE_PIN F14 [get_ports {segment_output[2]}]
set_property PACKAGE_PIN F16 [get_ports {segment_output[3]}]
set_property PACKAGE_PIN E17 [get_ports {segment_output[4]}]
set_property PACKAGE_PIN C14 [get_ports {segment_output[5]}]
set_property PACKAGE_PIN C15 [get_ports {segment_output[6]}]

set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {digit_select_output[7]}]

set_property PACKAGE_PIN C19 [get_ports {digit_select_output[0]}]
set_property PACKAGE_PIN E19 [get_ports {digit_select_output[1]}]
set_property PACKAGE_PIN D19 [get_ports {digit_select_output[2]}]
set_property PACKAGE_PIN F18 [get_ports {digit_select_output[3]}]
set_property PACKAGE_PIN E18 [get_ports {digit_select_output[4]}]
set_property PACKAGE_PIN B20 [get_ports {digit_select_output[5]}]
set_property PACKAGE_PIN A20 [get_ports {digit_select_output[6]}]
set_property PACKAGE_PIN A18 [get_ports {digit_select_output[7]}]


#mode input switch and output led
set_property IOSTANDARD LVCMOS33 [get_ports {test_number[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_number[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {test_number[2]}]
set_property PACKAGE_PIN Y7 [get_ports {test_number[0]}]
set_property PACKAGE_PIN W9 [get_ports {test_number[1]}]
set_property PACKAGE_PIN Y9 [get_ports {test_number[2]}]


set_property IOSTANDARD LVCMOS15 [get_ports confirm_button]
set_property PACKAGE_PIN P1 [get_ports confirm_button]

#uart pin
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN Y19} [get_ports rx]
set_property -dict {IOSTANDARD LVCMOS33 PACKAGE_PIN V18} [get_ports tx]


set_false_path -from [get_clocks -of_objects [get_pins cpu_clk_inst/inst/plle2_adv_inst/CLKOUT1]] -to [get_clocks -of_objects [get_pins cpu_clk_inst/inst/plle2_adv_inst/CLKOUT0]]
set_false_path -from [get_clocks -of_objects [get_pins cpu_clk_inst/inst/plle2_adv_inst/CLKOUT0]] -to [get_clocks -of_objects [get_pins cpu_clk_inst/inst/plle2_adv_inst/CLKOUT1]]
